version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dedupdb
    ports:
      - "5433:5432"

  redis:
    image: redis

  migrate:
    build: .
    command: sh -c "npx prisma migrate deploy"
    depends_on:
      - postgres
    env_file:
      - .env

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - migrate
      - redis
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    command: npm run dev

  worker:
    build: .
    depends_on:
      - migrate
      - redis
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    command: npm run worker